### ISSUE TITLE
Problem with bodyWrapper

### ISSUE THREAD

**Issue by barti271** [kazagkazag/react-simple-table#13]
When custom bodyWrapper is used and when a user scrolls content of the table down to the bottom the following error is being thrown:

> VM6351:930 Uncaught TypeError: this.props.onScrollToBottom is not a function
>     at Table.onScroll (eval at <anonymous> (http://localhost:3000/main.js:6985:2), <anonymous>:930:29)

**Comment by kazagkazag** [comment]
I've merged your PR, thanks a lot!
