### ISSUE TITLE
Scrolling possibility

### ISSUE THREAD

**Issue by barti271** [kazagkazag/react-simple-table#9]
It would be nice to have a scroller just for table content. Currently in case of long tables it is not possible to keep header row always visible while scrolling the content.

Please add this feature and it will make this plugin even more awesome.

Good job!

**Comment by kazagkazag** [comment]
I will add possibility of defining custom wrapper for table body if `semantic` equals `false`. Thanks for that you will be able to wrap `body` in any component, especially custom scrollbars. Is that ok for you?

**Comment by kazagkazag** [comment]
Prop `bodyWrapper` added to the `Table`. Now you can wrap table body in any custom element, including scrollable div. Would it be sufficient for you?

**Comment by barti271** [comment]
Great!

That should work.

Thank you!
